name: Investigation
about: New investigation topic
description: File a investigation
title: "[Investigation]: "
labels: ["investigation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: What 
    attributes:
      label: Description
      description: Also tell us, what idea you have or what kind of tool/software we should look into.
      placeholder: My idea is...
      value: "My idea is..."
    validations:
      required: true
  - type: textarea
    id: link
    attributes:
      label: Link
      description: Please add a link if available below
