# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: code-analysis

on:
  push:
    branches:
      - $default-branch
  pull_request:
    branches:
      - $default-branch

jobs:
  sonarscan:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_CI_USER_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_URL }}
        with:
          args: >
            -Dsonar.projectKey=MV_${{ github.event.repository.name }}
            -Dsonar.sources=.
